### create
POST http://localhost:3000/api/v1/users?includeMeta=true
Content-Type: application/json

{
    "username": "brooks", 
    "realName" : "Brooks Hatlen",
    "email" : "brooks@shawshank.jail",
    "password": "Rock Hammer"
}

### login
# @name login
POST http://localhost:3000/api/v1/sessions
Content-Type: application/json

{
    "login": "brooks", 
    "password": "Rock Hammer",
    "sessionType" : "native"
}

### list
GET http://localhost:3000/api/v1/users
Content-Type: application/json

### get
GET http://localhost:3000/api/v1/users/{{login.response.body.$.props.userId}}?includeLinks=true&includeMeta=true 
Content-Type: application/json

### get options
GET http://localhost:3000/api/v1/users/options
Content-Type: application/json
Cookie: vingSessionId={{login.response.body.$.props.id}} 

### put
PUT http://localhost:3000/api/v1/users/{{login.response.body.$.props.userId}} 
Content-Type: application/json
Cookie: vingSessionId={{login.response.body.$.props.id}} 

{
    "useAsDisplayName": "email"
}

### get with auth
GET http://localhost:3000/api/v1/users/{{login.response.body.$.props.userId}}?includeOptions=true
Content-Type: application/json
Cookie: vingSessionId={{login.response.body.$.props.id}} 


### delete
DELETE http://localhost:3000/api/v1/users/{{login.response.body.$.props.userId}} 
Content-Type: application/json
Cookie: vingSessionId={{login.response.body.$.props.id}} 
