### create
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "username": "tommy", 
    "realName" : "Tommy Williams",
    "email" : "tommy@shawshank.jail",
    "password": "testpass" // Elmo Blatch
}

### list
GET http://localhost:3000/api/user?includeLinks=true
Content-Type: application/json