### createUser
POST http://localhost:3000/api/v1/user?includeMeta=true
Content-Type: application/json

{
    "username": "bhadley", 
    "realName" : "Byron Hadley",
    "email" : "captain@shawshank.jail",
    "password": "violence"
}

### log in and verify email

### login
# @name login
POST http://localhost:3000/api/v1/session?includeMeta=true
Content-Type: application/json

{
    "login": "bhadley", 
    "password": "violence",
    "sessionType" : "native"
}

### create key
# @name createKey
POST http://localhost:3000/api/v1/apikey?includeMeta=true
Content-Type: application/json

{
    "name": "test rest", 
    "reason" : "can we log in",
    "url" : "http://localhost",
    "userId" : "{{login.response.body.$.props.userId}}"
}

### listKeys
GET http://localhost:3000/api/v1/user/{{login.response.body.$.props.userId}}/apikeys
Content-Type: application/json

### get key
GET http://localhost:3000/api/v1/apikey/{{createKey.response.body.$.props.id}}?includeLinks=true&includeMeta=true&includeRelated=user 
Cookie: vingSessionId={{login.response.body.$.props.id}} 
Content-Type: application/json

### login with key
# @name loginWithKey
POST http://localhost:3000/api/v1/session?includeMeta=true
Content-Type: application/json

{
    "apiKey": "{{createKey.response.body.$.props.id}}", 
    "privateKey": "{{createKey.response.body.$.props.privateKey}}"
}

### get user using key
GET http://localhost:3000/api/v1/user/{{loginWithKey.response.body.$.props.userId}}?includeMeta=true
Content-Type: application/json
Cookie: vingSessionId={{loginWithKey.response.body.$.props.id}} 


### put user with key - should fail
PUT http://localhost:3000/api/v1/user/{{loginWithKey.response.body.$.props.userId}} 
Content-Type: application/json
Cookie: vingSessionId={{loginWithKey.response.body.$.props.id}} 

{
    "useAsDisplayName": "email"
}

### put user with key - should succeed
PUT http://localhost:3000/api/v1/user/{{login.response.body.$.props.userId}} 
Content-Type: application/json
Cookie: vingSessionId={{login.response.body.$.props.id}} 

{
    "useAsDisplayName": "email"
}


### delete key
DELETE http://localhost:3000/api/v1/apikey/{{createKey.response.body.$.props.id}} 
Content-Type: application/json
Cookie: vingSessionId={{login.response.body.$.props.id}} 
