import { encode, decode } from './base62.mjs';
import { encrypt, decrypt } from './skipjack.mjs';

/**
 * Generates an encrypted string from an integer. See the environment variable `VING_SKIPJACK_KEY`.
 * @param {number} int The number to be encrypted.
 * @returns {string} The resulting encrypted string. Note that this will be different for different sites based upon what is in `VING_SKIPJACK_KEY`.
 * @example
 * stringifyId(1) // vJH34sj3
 */
export const stringifyId = (int) => encode(encrypt(int));

/**
 * Unencrypts a string back to its original integer value.
 * @param {string} str The string generated by `stringifyId()`.
 * @returns {number} The original number passed to `stringifyId()`.
 * @example
 * parseId('vJH34sj3') // 1
 */
export const parseId = (str) => decrypt(decode(str));